### ISSUE TITLE
Crate status

### ISSUE THREAD

**Issue by r4v3n6101** [ewilken/hap-rs#92]
Hi! Is this crate alive? I doesn't see any activity in the past time. If it's not well maintained, could someone suggests me alternatives for HomeKit in the Rust language?

**Comment by ewilken** [comment]
Hi! This crate is somewhat alive, since people are apparently depending on and [working on it](https://github.com/ewilken/hap-rs/pull/89), however, unfortunately, I don't have a lot of time to dedicate to maintaining it myself at the moment, as life happens.

I'd be super happy to accept contributions, though, and I will keep this crate alive for as long as people need it. (Which might be related to people needing HomeKit at all, vs. using [Matter](https://github.com/project-chip/matter-rs).) Personally, I view Matter as the natural successor to HomeKit and think I might deprecate this crate in favor of the Rust implementation of Matter at some point.

**Comment by r4v3n6101** [comment]
Thanks for the answer! I guess I can close this issue, because I have no question anymore.
